version: '3'
services:
  zookeeper:
    image: zookeeper:3.7
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAMES=INSIDE
      - KAFKA_LISTENER_ORIGINS=INSIDE
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_LISTENER_HOSTNAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_NAME_INSIDE_PORT=9093
      - KAFKA_ADVERTISED_LISTENER_NAME=INSIDE
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
