server:
  port: 8761  # Default port for Eureka

spring:
  application:
    name: eureka-discovery  # Name of the application

eureka:
  client:
    registerWithEureka: false  # The Eureka server itself doesn't register with Eureka
    fetchRegistry: false        # We don't fetch the registry, because it's a server
  server:
    enableSelfPreservation: false  # Optional: Disables self-preservation mode